### ISSUE TITLE
Loading data from Magritek Spinsolve 

### ISSUE THREAD

**Issue by lpatiny** [cheminfo/nmr-load-save#220]
Jcamp file:

[nmr_fid.dx.zip](https://github.com/cheminfo/nmr-load-save/files/11748017/nmr_fid.dx.zip)

Expected result:

![image](https://github.com/cheminfo/nmr-load-save/assets/1484241/de96dbe7-c3c8-4378-b69d-aec9bf09a3d3)

Original files:

[Archive.zip](https://github.com/cheminfo/nmr-load-save/files/11748027/Archive.zip)

**Comment by jobo322** [comment]
I have some questions, 

- how do you calculate the `SW` LDR in the jcamp file. 
- can I use .SHIFT REFERENCE LDR, if yes, the index is related with the zero filled data that is related with the parameter `zero fill` in your `acqu.par`? this values is a factor? I mean if the number of complex points is 8192 in the FID, the zero filled will be 4 x 8192?

**Comment by targos** [comment]
I don't understand, you ask questions and 15 minutes later you close it without answers.

FWIW you can look at this code, where They handle some Jcamp fields: https://github.com/jjhelmus/nmrglue/blob/master/nmrglue/fileio/spinsolve.py

**Comment by jobo322** [comment]
seems it is a problem of connection, strange, because I did write this question this morning (yesterday evening your time). 

thanks for the link. I will check it tomorrow morning. I did support to `REFERENCE_POINT` LDR because the .SHIFT REFERENCE is only applicable if we have the `zero fill` parameter but it is not included in the jcamp file.
